web: gunicorn cpa_academy.wsgi:application --bind 0.0.0.0:$PORT --workers=${WEB_CONCURRENCY:-1} --threads=${GUNICORN_THREADS:-2} --timeout=${GUNICORN_TIMEOUT:-90} --graceful-timeout=${GUNICORN_GRACEFUL_TIMEOUT:-30} --keep-alive=${GUNICORN_KEEP_ALIVE:-5} --max-requests=${GUNICORN_MAX_REQUESTS:-1000} --max-requests-jitter=${GUNICORN_MAX_REQUESTS_JITTER:-100}



