# Generated by Django 5.2.7 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
